test

diff --git a/.github/workflows/pr-check.yml b/.github/workflows/pr-check.yml
--- a/.github/workflows/pr-check.yml
+++ b/.github/workflows/pr-check.yml
@@ -93,51 +93,51 @@ jobs:
               core.info('PR lint passed.');
             }
 
-  build:
-    name: Build ${{ matrix.os-name }}(JDK ${{ matrix.java }} / ${{ matrix.arch }})
-    needs: pr-lint
-    runs-on: ${{ matrix.runner }}
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          - java: '8'
-            runner: ubuntu-latest
-            os-name: ubuntu
-            arch: x86_64
-          - java: '17'
-            runner: ubuntu-24.04-arm
-            os-name: ubuntu
-            arch: aarch64
-          - java: '8'
-            runner: macos-26-intel
-            os-name: macos
-            arch: x86_64
-          - java: '17'
-            runner: macos-latest
-            os-name: macos
-            arch: aarch64
-
-    steps:
-      - uses: actions/checkout@v4
-
-      - name: Set up JDK ${{ matrix.java }}
-        uses: actions/setup-java@v4
-        with:
-          java-version: ${{ matrix.java }}
-          distribution: 'temurin'
-
-      - name: Cache Gradle packages
-        uses: actions/cache@v4
-        with:
-          path: |
-            ~/.gradle/caches
-            ~/.gradle/wrapper
-          key: ${{ runner.os }}-${{ matrix.arch }}-gradle-${{ hashFiles('**/*.gradle', '**/gradle-wrapper.properties') }}
-          restore-keys: ${{ runner.os }}-${{ matrix.arch }}-gradle-
-
-      - name: Build
-        run: ./gradlew clean build --no-daemon
+#  build:
+#    name: Build ${{ matrix.os-name }}(JDK ${{ matrix.java }} / ${{ matrix.arch }})
+#    needs: pr-lint
+#    runs-on: ${{ matrix.runner }}
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        include:
+#          - java: '8'
+#            runner: ubuntu-latest
+#            os-name: ubuntu
+#            arch: x86_64
+#          - java: '17'
+#            runner: ubuntu-24.04-arm
+#            os-name: ubuntu
+#            arch: aarch64
+#          - java: '8'
+#            runner: macos-26-intel
+#            os-name: macos
+#            arch: x86_64
+#          - java: '17'
+#            runner: macos-latest
+#            os-name: macos
+#            arch: aarch64
+#
+#    steps:
+#      - uses: actions/checkout@v4
+#
+#      - name: Set up JDK ${{ matrix.java }}
+#        uses: actions/setup-java@v4
+#        with:
+#          java-version: ${{ matrix.java }}
+#          distribution: 'temurin'
+#
+#      - name: Cache Gradle packages
+#        uses: actions/cache@v4
+#        with:
+#          path: |
+#            ~/.gradle/caches
+#            ~/.gradle/wrapper
+#          key: ${{ runner.os }}-${{ matrix.arch }}-gradle-${{ hashFiles('**/*.gradle', '**/gradle-wrapper.properties') }}
+#          restore-keys: ${{ runner.os }}-${{ matrix.arch }}-gradle-
+#
+#      - name: Build
+#        run: ./gradlew clean build --no-daemon
 
   docker-build-centos8:
     name: Build centos8 (JDK 8 / x86_64)
@@ -185,7 +185,10 @@ jobs:
         run: ./gradlew --stop || true
 
       - name: Build
-        run: ./gradlew clean build --no-daemon --no-build-cache
+        #run: ./gradlew clean build --no-daemon --no-build-cache
+        run: |
+          ./gradlew clean build -x test --no-daemon --no-build-cache
+          ./gradlew framework:test --tests org.tron.core.zksnark.ShieldedReceiveTest
 
       - name: Generate JaCoCo report
         run: ./gradlew jacocoTestReport --no-daemon --no-build-cache
@@ -200,49 +203,49 @@ jobs:
             **/build/test-results/**
           if-no-files-found: error
 
-  docker-build-debian11:
-    name: Build debian11 (JDK 8 / x86_64)
-    needs: pr-lint
-    runs-on: ubuntu-latest
-
-    container:
-      image: eclipse-temurin:8-jdk
-
-    defaults:
-      run:
-        shell: bash
-
-    env:
-      GRADLE_USER_HOME: /github/home/.gradle
-
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: Install dependencies (Debian + build tools)
-        run: |
-          set -euxo pipefail
-          apt-get update
-          apt-get install -y git wget unzip build-essential curl jq
-
-      - name: Check Java version
-        run: java -version
-
-      - name: Cache Gradle
-        uses: actions/cache@v4
-        with:
-          path: |
-            /github/home/.gradle/caches
-            /github/home/.gradle/wrapper
-          key: ${{ runner.os }}-debian11-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
-          restore-keys: |
-            ${{ runner.os }}-debian11-gradle-
-
-      - name: Grant execute permission
-        run: chmod +x gradlew
-
-      - name: Build
-        run: ./gradlew clean build --no-daemon
+#  docker-build-debian11:
+#    name: Build debian11 (JDK 8 / x86_64)
+#    needs: pr-lint
+#    runs-on: ubuntu-latest
+#
+#    container:
+#      image: eclipse-temurin:8-jdk
+#
+#    defaults:
+#      run:
+#        shell: bash
+#
+#    env:
+#      GRADLE_USER_HOME: /github/home/.gradle
+#
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v4
+#
+#      - name: Install dependencies (Debian + build tools)
+#        run: |
+#          set -euxo pipefail
+#          apt-get update
+#          apt-get install -y git wget unzip build-essential curl jq
+#
+#      - name: Check Java version
+#        run: java -version
+#
+#      - name: Cache Gradle
+#        uses: actions/cache@v4
+#        with:
+#          path: |
+#            /github/home/.gradle/caches
+#            /github/home/.gradle/wrapper
+#          key: ${{ runner.os }}-debian11-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
+#          restore-keys: |
+#            ${{ runner.os }}-debian11-gradle-
+#
+#      - name: Grant execute permission
+#        run: chmod +x gradlew
+#
+#      - name: Build
+#        run: ./gradlew clean build --no-daemon
 
 
   coverage-gate:
