fff

diff --git a/.github/workflows/pullrequesttarget.yml b/.github/workflows/pullrequesttarget.yml
--- a/.github/workflows/pullrequesttarget.yml
+++ b/.github/workflows/pullrequesttarget.yml
@@ -47,12 +47,11 @@ jobs:
           ignore_job_states: timed_out,failed
           output_path: artifacts
       - name: check result
-        run: |
-          echo "buildkite result is:  ${{ steps.download.outputs.build-state }}"
-#        if: steps.download.outputs.build-state != 'passed'
-#          run: |
-#            echo "buildkite result is:  ${{ steps.download.outputs.build-state }}"
-#            exit 1
+        if: steps.download.outputs.build-state != 'passed'
+          run: |
+            echo "failed !!!!"
+            echo "buildkite result is:  ${{ steps.download.outputs.build-state }}"
+            exit 1
 #  demo1:
 #    name: trigger debian unit test
 #    runs-on: ubuntu-latest
