fff

diff --git a/.github/workflows/pullrequesttarget.yml b/.github/workflows/pullrequesttarget.yml
--- a/.github/workflows/pullrequesttarget.yml
+++ b/.github/workflows/pullrequesttarget.yml
@@ -48,10 +48,10 @@ jobs:
           output_path: artifacts
       - name: check result
         if: steps.download.outputs.build-state != 'passed'
-          run: |
-            echo "failed !!!!"
-            echo "buildkite result is:  ${{ steps.download.outputs.build-state }}"
-            exit 1
+        run: |
+          echo "failed !!!!"
+          echo "buildkite result is:  ${{ steps.download.outputs.build-state }}"
+          exit 1
 #  demo1:
 #    name: trigger debian unit test
 #    runs-on: ubuntu-latest
