fix

diff --git a/.github/workflows/pullrequesttarget.yml b/.github/workflows/pullrequesttarget.yml
--- a/.github/workflows/pullrequesttarget.yml
+++ b/.github/workflows/pullrequesttarget.yml
@@ -85,20 +85,20 @@ jobs:
           buildkite_api_access_token: ${{ secrets.JUST_BUILD_KITE }}
           pipeline: "tronprotocol/build-on-debian-9-dot-8"
       - name: Download Buildkite Artifacts1
-          id: download1
-          uses: EnricoMi/download-buildkite-artifact-action@v1
-          with:
-            buildkite_token: ${{ secrets.READ_BUILD }}
-            buildkite_build_url: ${{ steps.build1.outputs.url }}
-            ignore_build_states: blocked,canceled,skipped,not_run
-            ignore_job_states: timed_out,failed
-            output_path: artifacts
+        id: download1
+        uses: EnricoMi/download-buildkite-artifact-action@v1
+        with:
+          buildkite_token: ${{ secrets.READ_BUILD }}
+          buildkite_build_url: ${{ steps.build1.outputs.url }}
+          ignore_build_states: blocked,canceled,skipped,not_run
+          ignore_job_states: timed_out,failed
+          output_path: artifacts
       - name: check result1
-          if: steps.download1.outputs.build-state != 'passed'
-          run: |
-            echo "failed !!!!"
-            echo "buildkite result is:  ${{ steps.download1.outputs.build-state }}"
-            exit 1
+        if: steps.download1.outputs.build-state != 'passed'
+        run: |
+          echo "failed !!!!"
+          echo "buildkite result is:  ${{ steps.download1.outputs.build-state }}"
+          exit 1
 #  demo2:
 #    name: trigger centos unit test
 #    runs-on: ubuntu-latest
